### ISSUE TITLE
CSDN博客需要会员才能查看

### ISSUE THREAD

**Issue by Wenju-Huang** [SainingZhang/DDAMFN#15]
作者您好，非常感谢您的工作。现在CSDN上需要充会员才能看到您https://qq742971636.blog.csdn.net/article/details/136841591 这篇博文，为了方便一下大家，您能不能把它转移到git上或者其他更友好点的平台上呢。
十分感谢！

**Comment by xiewende** [comment]
故意收费的

**Comment by sir-sun** [comment]
就算你充值了也看不到哈哈哈，还得继续付费

**Comment by SainingZhang** [comment]
非常不好意思，本文是热心网友总结的，并非我亲自所作，我会去与作者沟通，让文章能被大众看见。

**Comment by SainingZhang** [comment]
I think you can check this: https://qq742971636.blog.csdn.net/article/details/141253148.
