### ISSUE TITLE
MFN_msceleb.pth

### ISSUE THREAD

**Issue by amarnathreddy0201** [SainingZhang/DDAMFN#16]
Hi Sir/Mam,
what is the MFN_msceleb.pth ? and why we are using in the model.

**Comment by amarnathreddy0201** [comment]
affectnet8_test.py , rafdb_test.py and fer_Plus.py  files pth files not added. How can i Access .pth data.
I tested DDAMFN++ model with unknown data set i got Accuracy 8. How can i improve the model accuracy?

**Comment by SainingZhang** [comment]
Have you cropped the image？What data did you use?

**Comment by amarnathreddy0201** [comment]
I got good accuracy with DDAMFN++. I got it why accuracy is low and i corrected.
