### ISSUE TITLE
dataset structure  

### ISSUE THREAD

**Issue by yiw576064** [SainingZhang/DDAMFN#7]
"Hello, thank you very much for your work. Could you please provide the structure of the dataset?"

**Comment by xddun** [comment]
https://qq742971636.blog.csdn.net/article/details/136841591

**Comment by simon20010923** [comment]
Our new version DDAMFN++ is available in the folder https://github.com/simon20010923/DDAMFN/DDAMFN++, which includes new alignment code refer to https://github.com/biubug6/Pytorch_Retinaface and optimized by SAM ([Sharpness aware minimization for efficiently improving generalization](https://arxiv.org/abs/2010.01412)). The trained RAF-DB model is available in DDAMFN++/checkpoints_ver2.0, which is not our best. The affectnet model will soon be available.

**Comment by simon20010923** [comment]
Our new version DDAMFN++ is available in the folder https://github.com/simon20010923/DDAMFN/tree/main/DDAMFN%2B%2B, which includes new alignment code refer to https://github.com/biubug6/Pytorch_Retinaface and optimized by SAM ([Sharpness aware minimization for efficiently improving generalization](https://arxiv.org/abs/2010.01412)). The trained RAF-DB model is available in DDAMFN++/checkpoints_ver2.0, which is not our best. The affectnet model will soon be available.
